### ISSUE TITLE
Groovy's implicit variables in command line

### ISSUE THREAD

**Issue by abhi18av** [danielsun1106/groovy-option-support#1]
Hi @danielsun1106 :)

I've found you via the active committers on the Apache Groovy repo and I didn't really know who else to ask about groovy - you do seem to love groovy a lot.

So, the thing is I'm trying to port a bunch of **perl one liners to groovy ** and I'm kinda stuck at a few points - especially with the implicit variables.

Like, there's 

* `line` and `count`  in `-n ` and `-p` 
* `split` in `-a`

I need to know whether there're implicit variables like 

- `word` for processing every single word per line or otherwise
- *and many more* (?)

Sadly, even the official doc. mentions only the `line` and `split` only and there are only a couple blog posts regarding this. I tried going through the source code but being a n00b, it's a bit overwhelming for me. I'd greatly appreciate your help 😄

**Comment by daniellansun** [comment]
Hi Abhinav,

```
  Glad to know new contributor for Groovy :)

  I'll investigate it later because I am not beside my computer.
```

P.S.  Mailing list is a better place to discuss, and much more people will involve. FYI: 
http://groovy-lang.org/mailing-lists.html

Cheers,
Daniel.Sun

**Comment by daniellansun** [comment]
@abhi18av 
Hi Abhinav,

```
  Currently, only "count, split, out, line" implicit variables available, you can find them at:
```

https://github.com/apache/groovy/blob/master/src/main/groovy/ui/GroovyMain.java#L552

Cheers,
Daniel.Sun

**Comment by abhi18av** [comment]
Ah, thanks! This seems helpful but I'd definitely need to spend more time on it. I've joined the mailing list, would definitely like to put up these little facilities over there :)

Keep groovin' @danielsun1106 
- Abhinav

**Comment by daniellansun** [comment]
@abhi18av 
You're welcome ;)

**Comment by abhi18av** [comment]
Hi Daniel

Could you please tell me if there has been any update in the one-liners aspect of groovy?

I am unable to find any exhaustive list of implicit variable at all.
